# Generated by Django 2.1.1 on 2018-09-27 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fayl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ady', models.CharField(max_length=70)),
                ('Pdf', models.FileField(upload_to='')),
                ('Tertibi', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gosmaca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surat_tm', models.ImageField(blank=True, upload_to='Gosmaca')),
                ('Surat_en', models.ImageField(blank=True, upload_to='Gosmaca')),
                ('Surat_ru', models.ImageField(blank=True, upload_to='Gosmaca')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gosmaca_Ady',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ady', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ady', models.CharField(max_length=70)),
                ('Makala_tm', models.TextField(blank=True)),
                ('Makala_ru', models.TextField(blank=True)),
                ('Makala_en', models.TextField(blank=True)),
                ('Tertibi', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habar_Surat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Suraty', models.ImageField(blank=True, upload_to='Habar_Surat')),
                ('Habar_ady', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Habar')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ady', models.CharField(max_length=70)),
                ('Slug', models.CharField(default='', max_length=70)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Myhmanlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ip_adresleri', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Renk_Ady',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ady', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Renkler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Renk_kody', models.CharField(default=None, max_length=70)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Sayla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Renk_Ady')),
            ],
        ),
        migrations.CreateModel(
            name='Sahypa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ady', models.CharField(max_length=70)),
                ('Makala', models.TextField()),
                ('Tertibi', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Esasy_Slide', models.CharField(default='Esasy-Slide', max_length=70)),
                ('Slide1_1_tm', models.CharField(blank=True, max_length=100)),
                ('Slide1_1_ru', models.CharField(blank=True, max_length=100)),
                ('Slide1_1_en', models.CharField(blank=True, max_length=100)),
                ('Slide1_1_url', models.CharField(blank=True, max_length=100)),
                ('Slide1_1', models.ImageField(upload_to='SlideShow')),
                ('Slide1_2_tm', models.CharField(blank=True, max_length=100)),
                ('Slide1_2_ru', models.CharField(blank=True, max_length=100)),
                ('Slide1_2_en', models.CharField(blank=True, max_length=100)),
                ('Slide1_2_url', models.CharField(blank=True, max_length=100)),
                ('Slide1_2', models.ImageField(upload_to='SlideShow')),
                ('Slide1_3_tm', models.CharField(blank=True, max_length=100)),
                ('Slide1_3_ru', models.CharField(blank=True, max_length=100)),
                ('Slide1_3_en', models.CharField(blank=True, max_length=100)),
                ('Slide1_3_url', models.CharField(blank=True, max_length=100)),
                ('Slide1_3', models.ImageField(upload_to='SlideShow')),
                ('Slide2_1_tm', models.CharField(blank=True, max_length=100)),
                ('Slide2_1_ru', models.CharField(blank=True, max_length=100)),
                ('Slide2_1_en', models.CharField(blank=True, max_length=100)),
                ('Slide2_1_url', models.CharField(blank=True, max_length=100)),
                ('Slide2_1', models.ImageField(upload_to='SlideShow')),
                ('Slide2_2_tm', models.CharField(blank=True, max_length=100)),
                ('Slide2_2_ru', models.CharField(blank=True, max_length=100)),
                ('Slide2_2_en', models.CharField(blank=True, max_length=100)),
                ('Slide2_2_url', models.CharField(blank=True, max_length=100)),
                ('Slide2_2', models.ImageField(upload_to='SlideShow')),
                ('Slide2_3_tm', models.CharField(blank=True, max_length=100)),
                ('Slide2_3_ru', models.CharField(blank=True, max_length=100)),
                ('Slide2_3_en', models.CharField(blank=True, max_length=100)),
                ('Slide2_3_url', models.CharField(blank=True, max_length=100)),
                ('Slide2_3', models.ImageField(upload_to='SlideShow')),
                ('Slide3_1_tm', models.CharField(blank=True, max_length=100)),
                ('Slide3_1_ru', models.CharField(blank=True, max_length=100)),
                ('Slide3_1_en', models.CharField(blank=True, max_length=100)),
                ('Slide3_1_url', models.CharField(blank=True, max_length=100)),
                ('Slide3_1', models.ImageField(upload_to='SlideShow')),
                ('Slide3_2_tm', models.CharField(blank=True, max_length=100)),
                ('Slide3_2_ru', models.CharField(blank=True, max_length=100)),
                ('Slide3_2_en', models.CharField(blank=True, max_length=100)),
                ('Slide3_2_url', models.CharField(blank=True, max_length=100)),
                ('Slide3_2', models.ImageField(upload_to='SlideShow')),
                ('Slide3_3_tm', models.CharField(blank=True, max_length=100)),
                ('Slide3_3_ru', models.CharField(blank=True, max_length=100)),
                ('Slide3_3_en', models.CharField(blank=True, max_length=100)),
                ('Slide3_3_url', models.CharField(blank=True, max_length=100)),
                ('Slide3_3', models.ImageField(upload_to='SlideShow')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ady', models.CharField(max_length=70)),
                ('Surat', models.ImageField(blank=True, upload_to='Albom')),
                ('Tertibi', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='TDSGZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tm', models.CharField(default='', max_length=170)),
                ('Ru', models.CharField(default='', max_length=170)),
                ('En', models.CharField(default='', max_length=170)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ady', models.CharField(max_length=70)),
                ('Vidyo', models.FileField(upload_to='')),
                ('Tertibi', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Menu')),
            ],
        ),
        migrations.AddField(
            model_name='habar',
            name='Menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Menu'),
        ),
        migrations.AddField(
            model_name='gosmaca',
            name='Sayla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Gosmaca_Ady'),
        ),
        migrations.AddField(
            model_name='fayl',
            name='Menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Menu'),
        ),
    ]
