# Generated by Django 2.1.1 on 2018-09-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_auto_20180928_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gif_lar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bas_Arkafon', models.ImageField(upload_to='Gif_lar')),
                ('Bas_Usti', models.ImageField(upload_to='Gif_lar')),
                ('Bas_Gif', models.ImageField(upload_to='Gif_lar')),
                ('Media_Surat', models.ImageField(upload_to='Gif_lar')),
                ('Media_Video', models.ImageField(upload_to='Gif_lar')),
            ],
        ),
    ]
