# Generated by Django 2.1.1 on 2018-09-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0004_gif_lar'),
    ]

    operations = [
        migrations.AddField(
            model_name='gif_lar',
            name='Ady',
            field=models.CharField(default='', max_length=70),
        ),
    ]
