# Generated by Django 2.1.1 on 2018-09-29 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0005_gif_lar_ady'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Ady',
            new_name='Ady_tm',
        ),
    ]
