# Generated by Django 2.1.1 on 2018-09-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0006_auto_20180929_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Ady_en',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='menu',
            name='Ady_ru',
            field=models.CharField(default='', max_length=70),
        ),
    ]
