# Generated by Django 2.1.1 on 2018-09-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0008_menu_sahypa_suraty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habar',
            name='Okalan',
            field=models.IntegerField(default=0),
        ),
    ]
