# Generated by Django 2.1.1 on 2018-09-30 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0009_auto_20180929_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habar',
            old_name='Ady',
            new_name='Ady_tm',
        ),
    ]
