# Generated by Django 2.1.1 on 2018-09-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0010_auto_20180930_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='habar',
            name='Ady_en',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='habar',
            name='Ady_ru',
            field=models.CharField(default='', max_length=70),
        ),
    ]
