# Generated by Django 2.1.1 on 2018-09-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0011_auto_20180930_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habar',
            name='Tertibi',
        ),
        migrations.AddField(
            model_name='habar',
            name='Mohum',
            field=models.BooleanField(default=0),
        ),
    ]
