# Generated by Django 2.1.1 on 2018-09-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0012_auto_20180930_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='habar',
            name='Esasy_Surat',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
