# Generated by Django 2.1.1 on 2018-10-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0013_habar_esasy_surat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fayl',
            name='Menu',
        ),
        migrations.RemoveField(
            model_name='fayl',
            name='Tertibi',
        ),
        migrations.AddField(
            model_name='fayl',
            name='Ikonka',
            field=models.ImageField(blank=True, upload_to='Kitaplar'),
        ),
        migrations.AddField(
            model_name='fayl',
            name='Mazmun',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fayl',
            name='Pdf',
            field=models.FileField(upload_to='Kitaplar'),
        ),
    ]
