# Generated by Django 2.1.1 on 2018-10-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0015_auto_20181002_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorag_Jogap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sorag_tm', models.CharField(max_length=70)),
                ('Jogap_tm', models.TextField()),
                ('Sorag_ru', models.CharField(max_length=70)),
                ('Jogap_ru', models.TextField()),
                ('Sorag_en', models.CharField(max_length=70)),
                ('Jogap_en', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
