# Generated by Django 2.1.1 on 2018-10-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0017_auto_20181003_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='albom',
            name='Esasy_Surat',
            field=models.ImageField(blank=True, upload_to='Albom'),
        ),
    ]
