# Generated by Django 2.1.1 on 2018-10-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0018_albom_esasy_surat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albom',
            name='Ady',
        ),
        migrations.AddField(
            model_name='albom',
            name='Ady_en',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='albom',
            name='Ady_ru',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='albom',
            name='Ady_tm',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='video',
            name='Vidyo_Surat',
            field=models.ImageField(blank=True, upload_to='Video'),
        ),
    ]
