# Generated by Django 2.1.1 on 2018-10-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0020_auto_20181004_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habar',
            name='Esasy_Surat',
            field=models.ImageField(blank=True, upload_to='Habar'),
        ),
    ]
