# Generated by Django 2.1.1 on 2018-10-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0021_auto_20181005_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Habar',
            field=models.BooleanField(default=False),
        ),
    ]
