# Generated by Django 2.1.1 on 2018-10-05 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0022_menu_habar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habar',
            name='Menu',
            field=models.ForeignKey(limit_choices_to={'Habar': True}, on_delete=django.db.models.deletion.CASCADE, to='new.Menu'),
        ),
    ]
